-- 出游故事时间轴与时间胶囊：请在获得站点所有者确认后，于 Supabase SQL Editor 执行。
alter table public.love_records add column if not exists city text;
alter table public.love_records add column if not exists moods jsonb not null default '[]'::jsonb;
alter table public.love_records add column if not exists photos jsonb not null default '[]'::jsonb;

create table if not exists public.love_capsules (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  photos jsonb not null default '[]'::jsonb,
  unlock_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.love_capsules enable row level security;
drop policy if exists "Public read love_capsules" on public.love_capsules;
drop policy if exists "Public insert love_capsules" on public.love_capsules;
drop policy if exists "Public update love_capsules" on public.love_capsules;
drop policy if exists "Public delete love_capsules" on public.love_capsules;
create policy "Public read love_capsules" on public.love_capsules for select using (true);
create policy "Public insert love_capsules" on public.love_capsules for insert with check (true);
create policy "Public update love_capsules" on public.love_capsules for update using (true) with check (true);
create policy "Public delete love_capsules" on public.love_capsules for delete using (true);
